# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5732edeeb8543c381ad55eb028ab4c141a90e1a9ca60335411f117eaf11cdcc9d7c3199f33e7123ec5dc4de7bcf3c876aeba2eae9cc504101e21b3494b120b4

test:
  secret_key_base: d462c30780009afd0ba6eeca0562b47a55610208553b09537e56a5338b0d635574eaaf60335abeaeca026c911eabaf240c18bbb87766eeb9cc57e475834ecacc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
